# Generated by Django 5.1.7 on 2025-03-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacture',
            new_name='Manufacturer',
        ),
    ]
